const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src/schoolTaskService.js'), 'utf8');
const context = vm.createContext({ Date, crypto: require('node:crypto').webcrypto });
vm.runInContext(source.replace(/^import .*;$/gm, '').replaceAll('export ', ''), context);
const payload = values => context.schoolTaskPayload({ subject_id:'maths', assessment_name:'Algebra', assessment_type:'homework', status:'not_started', ...values });
assert.equal(payload({}).score, null);
assert.equal(payload({}).percentage, null);
assert.equal(payload({status:'completed',score:'0',max_score:'20'}).percentage, 0);
assert.equal(payload({status:'completed',score:'16',max_score:'20'}).percentage, 80);
assert.equal(payload({status:'completed',is_marked:'on'}).is_marked, true);
assert.throws(() => payload({score:'10',max_score:'20'}));
assert.throws(() => payload({status:'completed',score:'21',max_score:'20'}));
assert.throws(() => payload({status:'completed',score:'2',max_score:''}));
assert.throws(() => payload({status:'completed',score:'NaN',max_score:'20'}));
assert.equal(payload({status:'in_progress'}).completed_at, null);
console.log('10 school task validation checks passed.');
