import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT.parent / "outputs" / "tara-tsa-practice-app" / "tsa-section1-question-bank.json"
ASSET_DIR = ROOT / "question-assets"
OUT_BANK = ROOT / "src" / "questionBank.generated.js"
OUT_MANIFEST = ROOT / "src" / "questionBankManifest.generated.js"

TYPE_MAP = {
    "Identifying the Main Conclusion": "Main Conclusion",
    "Identifying an Assumption": "Assumption",
    "Assessing the Impact of Additional Evidence": "Additional Evidence / Strengthen / Weaken",
    "Detecting Flaws in Reasoning": "Flaw",
    "Identifying Parallel Reasoning": "Parallel Reasoning",
    "Drawing a Conclusion": "Drawing a Conclusion",
    "Matching Principles": "Matching Principles",
    "Selecting Relevant Information": "Selecting Relevant Information",
    "Finding Procedures": "Finding Procedures",
    "Identifying Similarity": "Identifying Similarity",
}

FAMILY_MAP = {
    "Critical Reasoning": "Critical Reasoning",
    "Numerical Reasoning": "Problem Solving",
}


def option_object(options):
    labels = ["A", "B", "C", "D", "E"]
    return {label: str(options[index]).strip() for index, label in enumerate(labels) if index < len(options)}


def normalize_question(item):
    visual_assets = []
    for visual in item.get("visuals", []) or []:
        name = Path(visual.get("src", "")).name
        if name and (ASSET_DIR / name).exists():
            visual_assets.append({
                "src": f"question-assets/{name}",
                "alt": visual.get("alt") or f"{item['paper']} Question {item['questionNumber']} visual",
            })

    old_type = item.get("questionType") or item.get("type")
    official_type = TYPE_MAP.get(old_type, old_type)
    family = FAMILY_MAP.get(item.get("category"), item.get("category") or "Critical Reasoning")

    return {
        "id": item["id"],
        "paper": item.get("paper"),
        "paper_year": item.get("year"),
        "question_number": item.get("questionNumber"),
        "section": item.get("section", "Section 1"),
        "family": family,
        "official_question_type": official_type,
        "reasoning_pattern": item.get("specificPattern") or item.get("pattern"),
        "difficulty": item.get("difficulty", "Medium"),
        "question_text": item.get("question", "").strip(),
        "answer_options": option_object(item.get("options", [])),
        "correct_answer": item.get("answer"),
        "explanation": item.get("explanation", ""),
        "methodology": item.get("approach", ""),
        "relevant_question_highlights": item.get("keyParts") or [],
        "coaching_steps": item.get("coachingMethod") or [],
        "visuals": visual_assets,
    }


def main():
    raw = json.loads(SOURCE.read_text(encoding="utf-8"))
    questions = [normalize_question(item) for item in raw]
    manifest = {
        "totalQuestions": len(questions),
        "years": sorted({str(q["paper_year"]) for q in questions}, key=lambda value: (value == "specimen", value)),
        "visualQuestionCount": sum(1 for q in questions if q["visuals"]),
        "families": sorted({q["family"] for q in questions}),
        "officialTypes": sorted({q["official_question_type"] for q in questions}),
        "patterns": sorted({q["reasoning_pattern"] for q in questions}),
    }

    OUT_BANK.write_text(
        "// Generated by scripts/import-question-bank.py. Do not edit manually.\n"
        f"export const generatedQuestionBank = {json.dumps(questions, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    OUT_MANIFEST.write_text(
        "// Generated by scripts/import-question-bank.py. Do not edit manually.\n"
        f"export const questionBankManifest = {json.dumps(manifest, ensure_ascii=False, indent=2)};\n",
        encoding="utf-8",
    )
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
