// Summarised from the supplied Edexcel 8FM0 Issue 5, July 2025, PDF pages 12-32.
// Paper 2 options are alternatives, not a requirement to study every option.
export const FURTHER_MATHS_ROWS = [
  ['Core Pure','1','Proof',['Induction: series, divisibility and powers of matrices']],
  ['Core Pure','2','Complex numbers',['Solving quadratic, cubic and quartic equations','Complex arithmetic; real and imaginary parts',
    'Complex conjugates and conjugate roots','Argand diagrams','Cartesian and modulus-argument forms','Products and quotients in modulus-argument form','Loci and regions in Argand diagrams']],
  ['Core Pure','3','Matrices',['Matrix arithmetic and scalar multiples','Zero and identity matrices','Linear transformations in 2D and 3D',
    'Invariant points and lines','Determinants and scale factors','Singular matrices and inverses','Solving three simultaneous equations','Geometrical interpretation of three planes']],
  ['Core Pure','4','Further algebra and functions',['Polynomial roots and coefficients','Equations with transformed roots','Sums of integers, squares, cubes and related series']],
  ['Core Pure','5','Further calculus',['Volumes of revolution']],
  ['Core Pure','6','Further vectors',['Lines in 3D: vector and Cartesian forms','Equations of planes','Scalar products, plane equations and angles','Perpendicular vectors','Intersections and perpendicular distances']],
  ['Further Pure 1 (optional)','1','Further trigonometry',['T-formulae','T-formulae in identities','T-formulae in equations']],
  ['Further Pure 1 (optional)','2','Coordinate systems',['Parabola and rectangular hyperbola: Cartesian equations','Parametric equations','Focus-directrix property','Tangents and normals','Loci problems']],
  ['Further Pure 1 (optional)','3','Further vectors',['Vector product','Applications of vector product','Scalar triple product']],
  ['Further Pure 1 (optional)','4','Numerical methods',['Numerical solutions of first- and second-order differential equations']],
  ['Further Pure 1 (optional)','5','Inequalities',['Algebraic inequalities and inequations']],
  ['Further Pure 2 (optional)','1','Groups',['Group axioms','Examples, Cayley tables and cyclic groups','Orders and subgroups',"Lagrange's theorem"]],
  ['Further Pure 2 (optional)','2','Further matrix algebra',['Eigenvalues and eigenvectors','Diagonalisation','Cayley-Hamilton theorem']],
  ['Further Pure 2 (optional)','3','Further complex numbers',['Further Argand loci and regions']],
  ['Further Pure 2 (optional)','4','Number theory',['Division theorem, Euclidean algorithm and congruences',"Bezout's identity",'Modular arithmetic','Divisibility tests']],
  ['Further Pure 2 (optional)','5','Further sequences and series',['First-order recurrence relations','Closed-form solutions','Induction proofs of closed forms']],
  ['Further Statistics 1 (optional)','1','Discrete probability distributions',['Mean, variance and expected values of functions']],
  ['Further Statistics 1 (optional)','2','Poisson and binomial distributions',['Poisson distribution and additive property','Binomial and Poisson mean and variance','Poisson approximation to binomial','Hypothesis tests for a Poisson mean']],
  ['Further Statistics 1 (optional)','3','Chi-squared tests',['Goodness of fit, contingency tables, hypotheses and degrees of freedom']],
  ['Further Statistics 2 (optional)','1','Linear regression',['Least-squares regression','Residuals and residual sum of squares']],
  ['Further Statistics 2 (optional)','2','Continuous probability distributions',['Continuous variables, density and cumulative distributions','Relationship between density and cumulative functions','Mean, variance, expected values, percentiles and skewness','Continuous uniform distribution']],
  ['Further Statistics 2 (optional)','3','Correlation',['Product moment correlation',"Spearman's rank correlation",'Tests for zero correlation']],
  ['Further Mechanics 1 (optional)','1','Momentum and impulse',['Impulse-momentum principle and conservation of momentum']],
  ['Further Mechanics 1 (optional)','2','Work, energy and power',['Kinetic/potential energy, work-energy principle and conservation']],
  ['Further Mechanics 1 (optional)','3','Elastic collisions in one dimension',["Direct impact, Newton's restitution law and energy loss",'Successive impacts of spheres and smooth planes']],
  ['Further Mechanics 2 (optional)','1','Motion in a circle',['Angular speed, radial acceleration and horizontal circular motion']],
  ['Further Mechanics 2 (optional)','2','Centres of mass of plane figures',['Moments and discrete mass distributions','Uniform/composite figures, frameworks and equilibrium']],
  ['Further Mechanics 2 (optional)','3','Further kinematics',['Straight-line acceleration as a function of time or velocity']],
  ['Decision 1 (optional)','1','Algorithms and graph theory',['Algorithms and flowcharts','Bin packing, bubble sort and quick sort','Eulerian and semi-Eulerian graphs']],
  ['Decision 1 (optional)','2','Algorithms on graphs',["Minimum spanning trees: Prim and Kruskal","Shortest paths: Dijkstra"]],
  ['Decision 1 (optional)','3','Algorithms on graphs II',['Route inspection algorithm']],
  ['Decision 1 (optional)','4','Critical path analysis',['Activity networks from precedence tables','Precedence tables from networks','Critical paths and earliest/latest times','Total float and Gantt charts']],
  ['Decision 1 (optional)','5','Linear programming',['Formulating linear programmes','Graphical solutions, objective lines, vertices and integer solutions']],
  ['Decision 2 (optional)','1','Allocation problems',['Cost matrices and Hungarian algorithm for minimum cost or maximum profit']],
  ['Decision 2 (optional)','2','Flows in networks',['Cuts and capacity','Labelling procedure and augmenting flows','Max-flow min-cut theorem']],
  ['Decision 2 (optional)','3','Game theory',['Two-person zero-sum games and pay-off matrices','Play-safe strategies and saddle points','Optimal mixed strategies using graphs']],
  ['Decision 2 (optional)','4','Recurrence relations',['Modelling with recurrence relations','First-order linear homogeneous and non-homogeneous solutions']]
];
